# Generated by Django 3.2 on 2021-05-05 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('glasses', models.ManyToManyField(to='blog.Glasses')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.shape')),
            ],
        ),
        migrations.AddField(
            model_name='glasses',
            name='shape',
            field=models.ManyToManyField(to='blog.Shape'),
        ),
    ]
