# Generated by Django 3.2 on 2021-05-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphoto',
            name='shape',
        ),
    ]
