# Generated by Django 3.2 on 2021-05-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userphoto_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='glasses',
            field=models.ManyToManyField(null=True, to='blog.Glasses'),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='shape',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.shape'),
        ),
    ]
