# Generated by Django 3.2 on 2021-05-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210506_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='glasses',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
